import "@znode/base-components/tailwind-config/global.css";
import { getPortalHeader } from "@znode/utils/server";

export const metadata = {
  title: "Welcome to page-builder",
  description: "Generated by create-nx-workspace",
};

interface IRootLayoutProps {
  children: React.ReactNode;
}
export default async function RootLayout({ children }: IRootLayoutProps) {
  const themeName = (await getPortalHeader()).themeName || (process.env.DEFAULT_THEME as string);

  const theme = {
    "data-theme": themeName.toLocaleLowerCase(),
  };

  return (
    <html lang="en-US" {...theme}>
      <head>
      <link rel="stylesheet" href="/api/store-css" />
      </head>
      <body>
        {children}
        <div id="modal"></div>
      </body>
    </html>
  );
}
