//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

import * as Models from "../../types/multifront-types";
import { addCacheOption, buildEndpointQueryString, getHeaders } from "./base";
import { FilterTuple } from "../../types/multifront-types";
import * as MultifrontTypes from "../../types/multifront-types";

import { customFetch } from "../../common/customFetch";
const baseUrl = process.env.API_URL;

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

/**
 * Create Url Redirect.
 * @param body (optional) Url Redirect Model.
 * @return OK
 */

export async function UrlRedirect_create(body: Models.UrlRedirectModel | undefined): Promise<MultifrontTypes.UrlRedirectResponse> {
  let url_ = baseUrl + "UrlRedirect/Create";

  url_ = url_.replace(/[?&]$/, "");

  const content_ = JSON.stringify(body);

  let options_: RequestInit = {
    body: content_,
    method: "POST",
    cache: "no-store",
    headers: await getHeaders("POST", String(baseUrl)),
  };

  return customFetch(url_, options_, "UrlRedirect_create").then((_response: Response) => {
    return UrlRedirect_processCreate(_response);
  });
}

function UrlRedirect_processCreate(response: Response): Promise<MultifrontTypes.UrlRedirectResponse> {
  const status = response.status;
  let _headers: any = {};
  if (response.headers && response.headers.forEach) {
    response.headers.forEach((v: any, k: any) => (_headers[k] = v));
  }
  if (status === 200) {
    return response.text().then((_responseText) => {
      let result200: any = null;
      result200 = _responseText === "" ? null : (JSON.parse(_responseText) as Models.UrlRedirectResponse);
      return result200;
    });
  } else if (status === 201) {
    return response.text().then((_responseText) => {
      let result201: any = null;
      result201 = _responseText === "" ? null : (JSON.parse(_responseText) as Models.UrlRedirectResponse);
      return result201;
    });
  } else if (status !== 200 && status !== 204) {
    return response.text().then((_responseText) => {
      return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    });
  }
  return Promise.resolve<any>(null as any);
}

/**
 * Get Url Redirect List.
 * @param filter (optional)
 * @return OK
 */

export async function UrlRedirect_getUrlRedirectList(filter: FilterTuple[] | undefined): Promise<MultifrontTypes.UrlRedirectResponse> {
  let options_: RequestInit = {
    method: "GET",
    cache: "no-store",
    headers: await getHeaders("GET", String(baseUrl)),
  };

  let url_ = baseUrl + "UrlRedirect/GetUrlRedirectList";

  url_ += buildEndpointQueryString({ filter });

  if (filter === null) throw new Error("The parameter 'filter' cannot be null.");

  url_ = url_.replace(/[?&]$/, "");

  return customFetch(url_, options_, "UrlRedirect_getUrlRedirectList").then((_response: Response) => {
    return UrlRedirect_processGetUrlRedirectList(_response);
  });
}

function UrlRedirect_processGetUrlRedirectList(response: Response): Promise<MultifrontTypes.UrlRedirectResponse> {
  const status = response.status;
  let _headers: any = {};
  if (response.headers && response.headers.forEach) {
    response.headers.forEach((v: any, k: any) => (_headers[k] = v));
  }
  if (status === 200) {
    return response.text().then((_responseText) => {
      let result200: any = null;
      result200 = _responseText === "" ? null : (JSON.parse(_responseText) as Models.UrlRedirectResponse);
      return result200;
    });
  } else if (status === 204) {
    return response.text().then((_responseText) => {
      return throwException("No Content", status, _responseText, _headers);
    });
  } else if (status !== 200 && status !== 204) {
    return response.text().then((_responseText) => {
      return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    });
  }
  return Promise.resolve<any>(null as any);
}

/**
 * Get url redirect.
 * @param expand (optional)
 * @param filter (optional)
 * @return OK
 */

export async function UrlRedirect_getUrlRedirect(expand: string[] | undefined, filter: FilterTuple[] | undefined): Promise<MultifrontTypes.UrlRedirectResponse> {
  let options_: RequestInit = {
    method: "GET",
    cache: "no-store",
    headers: await getHeaders("GET", String(baseUrl)),
  };

  let url_ = baseUrl + "UrlRedirect/GetUrlRedirect";

  url_ += buildEndpointQueryString({ expand, filter });

  if (expand === null) throw new Error("The parameter 'expand' cannot be null.");
  if (filter === null) throw new Error("The parameter 'filter' cannot be null.");
  url_ = url_.replace(/[?&]$/, "");

  return customFetch(url_, options_, "UrlRedirect_getUrlRedirect").then((_response: Response) => {
    return UrlRedirect_processGetUrlRedirect(_response);
  });
}

function UrlRedirect_processGetUrlRedirect(response: Response): Promise<MultifrontTypes.UrlRedirectResponse> {
  const status = response.status;
  let _headers: any = {};
  if (response.headers && response.headers.forEach) {
    response.headers.forEach((v: any, k: any) => (_headers[k] = v));
  }
  if (status === 200) {
    return response.text().then((_responseText) => {
      let result200: any = null;
      result200 = _responseText === "" ? null : (JSON.parse(_responseText) as Models.UrlRedirectResponse);
      return result200;
    });
  } else if (status === 204) {
    return response.text().then((_responseText) => {
      return throwException("No Content", status, _responseText, _headers);
    });
  } else if (status !== 200 && status !== 204) {
    return response.text().then((_responseText) => {
      return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    });
  }
  return Promise.resolve<any>(null as any);
}

/**
 * Update url redirect.
 * @param body (optional) model to update.
 * @return OK
 */

export async function UrlRedirect_update(body: Models.UrlRedirectModel | undefined): Promise<MultifrontTypes.UrlRedirectResponse> {
  let url_ = baseUrl + "UrlRedirect/Update";

  url_ = url_.replace(/[?&]$/, "");

  const content_ = JSON.stringify(body);

  let options_: RequestInit = {
    body: content_,
    method: "PUT",
    headers: await getHeaders("PUT", String(baseUrl)),
    next: { revalidate: 0 },
  };

  return customFetch(url_, options_, "UrlRedirect_update").then((_response: Response) => {
    return UrlRedirect_processUpdate(_response);
  });
}

function UrlRedirect_processUpdate(response: Response): Promise<MultifrontTypes.UrlRedirectResponse> {
  const status = response.status;
  let _headers: any = {};
  if (response.headers && response.headers.forEach) {
    response.headers.forEach((v: any, k: any) => (_headers[k] = v));
  }
  if (status === 200) {
    return response.text().then((_responseText) => {
      let result200: any = null;
      result200 = _responseText === "" ? null : (JSON.parse(_responseText) as Models.UrlRedirectResponse);
      return result200;
    });
  } else if (status === 201) {
    return response.text().then((_responseText) => {
      let result201: any = null;
      result201 = _responseText === "" ? null : (JSON.parse(_responseText) as Models.UrlRedirectResponse);
      return result201;
    });
  } else if (status !== 200 && status !== 204) {
    return response.text().then((_responseText) => {
      return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    });
  }
  return Promise.resolve<any>(null as any);
}

/**
 * Delete Url Redirect.
 * @param body (optional) Url Redirect Id.
 * @return OK
 */

export async function UrlRedirect_delete(body: Models.ParameterModel | undefined): Promise<MultifrontTypes.TrueFalseResponse> {
  let url_ = baseUrl + "UrlRedirect/Delete";

  url_ = url_.replace(/[?&]$/, "");

  const content_ = JSON.stringify(body);

  let options_: RequestInit = {
    body: content_,
    method: "POST",
    cache: "no-store",
    headers: await getHeaders("POST", String(baseUrl)),
  };

  return customFetch(url_, options_, "UrlRedirect_delete").then((_response: Response) => {
    return UrlRedirect_processDelete(_response);
  });
}

function UrlRedirect_processDelete(response: Response): Promise<MultifrontTypes.TrueFalseResponse> {
  const status = response.status;
  let _headers: any = {};
  if (response.headers && response.headers.forEach) {
    response.headers.forEach((v: any, k: any) => (_headers[k] = v));
  }
  if (status === 200) {
    return response.text().then((_responseText) => {
      let result200: any = null;
      result200 = _responseText === "" ? null : (JSON.parse(_responseText) as Models.TrueFalseResponse);
      return result200;
    });
  } else if (status !== 200 && status !== 204) {
    return response.text().then((_responseText) => {
      return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    });
  }
  return Promise.resolve<any>(null as any);
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any }, result?: any): any {
  try {
    if (result !== null && result !== undefined) throw result;
    else throw new Error(message);
  } catch (ex) {
    const parsedRes = response === "" ? null : (JSON.parse(response) as any);
    return parsedRes;
  }
}
