const MY_ACCOUNT_ROUTES = {
  EDIT_PROFILE: "account/edit-profile",
  CHANGE_PASSWORD: "account/change-password",
  DASHBOARD: "account/dashboard",
  ACCOUNT_INFORMATION: "account/account-information",
  ACCOUNT_USERS: "account/account-users",
  ACCOUNT_ORDERS: "account/account-orders",
  ORDER_HISTORY: "account/order/list",
  PREVIOUS_PURCHASE: "account/previous-purchases",
  ORDER_DETAILS: "account/order/details",
  PENDING_ORDER: "account/pending-order",
  RETURN_ORDER: "account/return-order",
  QUOTE_ORDER: "account/quote/list",
  QUOTE_DETAILS: "account/quote/details",
  WISHLIST: "account/wishlist",
  VOUCHER_HISTORY: "account/voucher/list",
  VOUCHER_DETAILS: "account/voucher/details",
  REVIEW_HISTORY: "account/review-history",
  SAVE_CREDIT_CARD: "account/saved-card",
  ADDRESS_BOOK: "account/address-book",
  ADD_EDIT_ADDRESS_BOOK: "account/address-book/add-edit-address",
  CREATE_ORDER_TEMPLATE: "account/order-templates/create",
  SAVE_CART: "account/saved-cart/list",
  SAVE_CART_EDIT: "account/saved-cart/edit",
  PENDING_ORDER_HISTORY: "account/pending-order/list",
  PENDING_ORDER_DETAILS: "account/pending-order/details",
  PENDING_PAYMENT_HISTORY: "account/pending-payment/list",
  PENDING_PAYMENT_DETAILS: "account/pending-payment/details",
  ORDER_TEMPLATES: "account/order-templates/list",
  B_STORE_REGISTRATION: "account/b-store-registration",
  MANAGE_B_STORE: "account/manage-b-store",
};
export { MY_ACCOUNT_ROUTES };
