export const ADDRESS = {
  SUCCESS_DELETE_ADDRESS: "successDeleteAddress",
  ERROR_DELETE_SHIPPING_ADDRESS_AND_DELETE_BILLING_ADDRESS: "errorDeleteShippingAddressAndDeleteBillingAddress",
  ERROR_DELETE_SHIPPING_ADDRESS: "errorDeleteShippingAddress",
  ERROR_DELETE_BILLING_ADDRESS: "errorDeleteBillingAddress",
  ERROR_DELETE_ADDRESS: "errorDeleteAddress",
  ADMINISTRATOR_ROLE_NAME: "Administrator",
  MANAGER_ROLE_NAME: "Manager",
  USER_ROLE_NAME: "User",
  USER_ADDRESS_SETTINGS: "UserAddressSettings",
  ENABLE_USER_SHIPPING_ADDRESS_SUGGESTION: "EnableUserShippingAddressSuggestion",
  BILLING_ADDRESS_TYPE: "billing",
  SHIPPING_ADDRESS_TYPE: "shipping",
  ADDRESS_BOOK_TYPE: "AddressBook",
  ONETIME_ADDRESS_IDS: "OneTimeAddressIds",
  ADD_ADDRESS: "Add",
  EDIT_ADDRESS: "Edit",
  GUEST: "Guest",
  RETAIL: "Retail",
  ENTER_ADDRESS: "EnteredAddress ",
  SUCCESS_ADDRESS_UPDATED: "successAddressUpdated",
  SUCCESS_ADDRESS_ADDED: "successAddressAdded",
  EDIT: "Edit",
  ADD: "Add",
  IS_BILLING_ADDRESS_OPTIONAL: "isBillingAddressOptional",
  COMMERCIAL: "commercial",
  RESIDENTIAL: "residential",
  ADDRESS_TYPE: "Address Type",
  LABEL_COMMERCIAL: "Commercial",
  LABEL_RESIDENTIAL: "Residential",
};
export const ROLE = {
  USER_B2B: "User",
  MANAGER_B2B: "Manager",
  LIST: ["Manager", "User", "Administrator"],
};
