const PENDING_APPROVAL_STATUS = {
  PENDING_ORDER: "pendingapproval",
  PENDING_PAYMENT: "pendingpayment",
  PENDING_ORDER_LABEL: "PENDING APPROVAL",
  PENDING_PAYMENT_LABEL: "Pending Payment",
  PENDING_ORDER_STATUS: "PENDINGAPPROVAL",
  PAYMENT: "Payment",
  STORE: "Store",
  USERS: "Users",
};

const APPROVAL_STATUS_LABEL = {
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  PENDING_APPROVAL: "PENDINGAPPROVAL",
};

export { PENDING_APPROVAL_STATUS, APPROVAL_STATUS_LABEL };
