const QUOTE_STATUS = {
  QUOTE_STATUS_CANCELED: "CANCELED",
  QUOTE_STATUS_SUBMIT: "SUBMITTED",
  QUOTE_STATUS_APPROVED: "APPROVED",
  QUOTE_STATUS_EXPIRED: "EXPIRED",
  QUOTE_STATUS_IN_REVIEW: "INREVIEW",
};

const QUOTE = {
  SHOW_SHIPPING_CONSTRAINT: "ShowShippingConstraint",
  TRUE_VALUE: "TrueValue",
};

export { QUOTE_STATUS, QUOTE };
