export const RETURN_ORDER = {
  RETURN_STATUS: "Not Submitted",
  NOT_SUBMITTED: "NOTSUBMITTED",
  SUBMITTED: "SUBMITTED",
  DISPLAY_DRAFT: false,
};

export const RETURN_ORDER_STATUS = {
  VALID_RETURN_ORDER_STATUS: ["SUBMITTED", "SHIPPED", "RECEIVED"],
  IN_VALID_RETURN_ORDER_LINE_ITEM_STATUS: ["REJECTED"],
  VALID_RETURN_ORDER_LINE_ITEM_STATUS: ["SUBMITTED", "SHIPPED"],
  IN_VALID_RETURN_ORDER_STATUS: ["REJECTED"],
};
