//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
import * as Models from "../multifront-types";
import { addCacheOption, getHeaders } from "../base";
import { FilterTuple } from "../multifront-types";
import * as MultifrontTypes from "../../../types/interface";

import { customFetch } from "../../../common/customFetch";
const baseUrl = process.env.API_URL;

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

/**
 * @return OK
 */

export async function FormWidgetConfigurations_formWidgetConfigurationsGetByStoreCode(
  storeCode: string,
  widgetKey: string,
  cacheInvalidator?: FilterTuple[] | undefined
): Promise<MultifrontTypes.FormAndEmailWidgetConfigrationResponse> {
  let options_: RequestInit = {
    method: "GET",
    cache: "no-store",
    headers: await getHeaders("GET", String(baseUrl)),
    next: { revalidate: 0 },
  };
  options_ = addCacheOption(cacheInvalidator ?? [], options_);

  let url_ = baseUrl + "v2/form-widget-configurations/{storeCode}/{widgetKey}";

  if (storeCode === undefined || storeCode === null) throw new Error("The parameter 'storeCode' must be defined.");
  url_ = url_.replace("{storeCode}", encodeURIComponent("" + storeCode));
  if (widgetKey === undefined || widgetKey === null) throw new Error("The parameter 'widgetKey' must be defined.");
  url_ = url_.replace("{widgetKey}", encodeURIComponent("" + widgetKey));
  url_ = url_.replace(/[?&]$/, "");

  return customFetch(url_, options_, "FormWidgetConfigurations_formWidgetConfigurationsGetByStoreCode").then((_response: Response) => {
    return FormWidgetConfigurations_processFormWidgetConfigurationsGetByStoreCode(_response);
  });
}

function FormWidgetConfigurations_processFormWidgetConfigurationsGetByStoreCode(response: Response): Promise<MultifrontTypes.FormAndEmailWidgetConfigrationResponse> {
  const status = response.status;
  let _headers: any = {};
  if (response.headers && response.headers.forEach) {
    response.headers.forEach((v: any, k: any) => (_headers[k] = v));
  }
  if (status === 200) {
    return response.text().then((_responseText) => {
      let result200: any = null;
      result200 = _responseText === "" ? null : (JSON.parse(_responseText) as MultifrontTypes.FormAndEmailWidgetConfigrationResponse);
      return result200;
    });
  } else if (status === 204) {
    return response.text().then((_responseText) => {
      let result204: any = null;
      result204 = _responseText === "" ? null : (JSON.parse(_responseText) as Models.ZnodeErrorDetail);
      return throwException("No Content", status, _responseText, _headers, result204);
    });
  } else if (status === 400) {
    return response.text().then((_responseText) => {
      let result400: any = null;
      result400 = _responseText === "" ? null : (JSON.parse(_responseText) as Models.ZnodeErrorDetail);
      return throwException("Bad Request", status, _responseText, _headers, result400);
    });
  } else if (status === 500) {
    return response.text().then((_responseText) => {
      let result500: any = null;
      result500 = _responseText === "" ? null : (JSON.parse(_responseText) as Models.ZnodeErrorDetail);
      return throwException("Internal Server Error", status, _responseText, _headers, result500);
    });
  } else if (status === 404) {
    return response.text().then((_responseText) => {
      let result404: any = null;
      result404 = _responseText === "" ? null : (JSON.parse(_responseText) as Models.ZnodeErrorDetail);
      return throwException("Not Found", status, _responseText, _headers, result404);
    });
  } else if (status !== 200 && status !== 204) {
    return response.text().then((_responseText) => {
      return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    });
  }
  return Promise.resolve<any>(null as any);
}

export interface FileParameter {
  data: any;
  fileName: string;
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any }, result?: any): any {
  try {
    if (result !== null && result !== undefined) throw result;
    else throw new Error(message);
  } catch (ex) {
    const parsedRes = response === "" ? null : (JSON.parse(response) as any);
    return parsedRes;
  }
}
