//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
import * as Models from "./multifront-types";
import { addCacheOption, buildEndpointQueryString, getHeaders } from "./base";
import { FilterTuple } from "./multifront-types";
import * as MultifrontTypes from "./multifront-types";

import { customFetch } from "../../common/customFetch";
const baseUrl = process.env.API_URL;

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

/**
 * Retrieve the highlight by highlightCode and productId.
 * @param highlightCode The highlightCode associated with the highlight.
 * @param productId The productId associated with the highlight.
 * @return Success (Indicates that the request was successfully executed and the response body returns the data in the HighlightModelResponse model.)
 */

export async function Highlights_withDescriptionByHighlightCode(
  highlightCode: string,
  productId: number,
  cacheInvalidator?: FilterTuple[] | undefined
): Promise<MultifrontTypes.HighlightModelResponse> {
  let options_: RequestInit = {
    method: "GET",
    cache: "no-store",
    headers: await getHeaders("GET", String(baseUrl)),
    next: { revalidate: 0 },
  };
  options_ = addCacheOption(cacheInvalidator ?? [], options_);

  let url_ = baseUrl + "v2/highlights/{highlightCode}/with-description";

  url_ += (url_.indexOf("?") === -1 ? "?" : "&") + "productId=" + encodeURIComponent("" + productId);

  if (highlightCode === undefined || highlightCode === null) throw new Error("The parameter 'highlightCode' must be defined.");
  url_ = url_.replace("{highlightCode}", encodeURIComponent("" + highlightCode));
  if (productId === undefined || productId === null) throw new Error("The parameter 'productId' must be defined and cannot be null.");
  else url_ = url_.replace(/[?&]$/, "");

  return customFetch(url_, options_, "Highlights_withDescriptionByHighlightCode").then((_response: Response) => {
    return Highlights_processWithDescriptionByHighlightCode(_response);
  });
}

function Highlights_processWithDescriptionByHighlightCode(response: Response): Promise<MultifrontTypes.HighlightModelResponse> {
  const status = response.status;
  let _headers: any = {};
  if (response.headers && response.headers.forEach) {
    response.headers.forEach((v: any, k: any) => (_headers[k] = v));
  }
  if (status === 200) {
    return response.text().then((_responseText) => {
      let result200: any = null;
      result200 = _responseText === "" ? null : (JSON.parse(_responseText) as Models.HighlightModelResponse);
      return result200;
    });
  } else if (status === 204) {
    return response.text().then((_responseText) => {
      let result204: any = null;
      result204 = _responseText === "" ? null : (JSON.parse(_responseText) as Models.ZnodeErrorDetail);
      return throwException(
        "No Content (Indicates that the request was successfully executed, but the response body does not contain any data.)",
        status,
        _responseText,
        _headers,
        result204
      );
    });
  } else if (status === 400) {
    return response.text().then((_responseText) => {
      let result400: any = null;
      result400 = _responseText === "" ? null : (JSON.parse(_responseText) as Models.ZnodeErrorDetail);
      return throwException("Bad Request (Indicates that the request contains invalid data.)", status, _responseText, _headers, result400);
    });
  } else if (status === 404) {
    return response.text().then((_responseText) => {
      let result404: any = null;
      result404 = _responseText === "" ? null : (JSON.parse(_responseText) as Models.ZnodeErrorDetail);
      return throwException("Not Found (Indicates that the server cannot find the requested resource.)", status, _responseText, _headers, result404);
    });
  } else if (status === 500) {
    return response.text().then((_responseText) => {
      let result500: any = null;
      result500 = _responseText === "" ? null : (JSON.parse(_responseText) as Models.ZnodeErrorDetail);
      return throwException("Server Error (Indicates that an error occurred on the server.)", status, _responseText, _headers, result500);
    });
  } else if (status !== 200 && status !== 204) {
    return response.text().then((_responseText) => {
      return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    });
  }
  return Promise.resolve<any>(null as any);
}

/**
 * Retrieve the highlights by highlight code.
 * @param highLightCode The code associated with the highlight to be retrieved, provided as a route parameter.
 * @param filter (optional) A collection of filters to apply when retrieving the address list.
 * @return Success(Indicates that the request is successfully executed and the response body return the data in CategoryListResponse model.)
 */

export async function Highlights_highlightsByHighLightCode(
  highLightCode: string,
  filter: FilterTuple[] | undefined,
  cacheInvalidator?: FilterTuple[] | undefined
): Promise<MultifrontTypes.HighlightCodeResponse> {
  let options_: RequestInit = {
    method: "GET",
    headers: await getHeaders("GET", String(baseUrl)),
    next: { revalidate: 0 },
  };
  options_ = addCacheOption(cacheInvalidator ?? [], options_);

  let url_ = baseUrl + "v2/highlights/{highLightCode}";

  url_ += buildEndpointQueryString({ filter });

  if (highLightCode === undefined || highLightCode === null) throw new Error("The parameter 'highLightCode' must be defined.");
  url_ = url_.replace("{highLightCode}", encodeURIComponent("" + highLightCode));
  if (filter === null) throw new Error("The parameter 'filter' cannot be null.");
  url_ = url_.replace(/[?&]$/, "");

  return customFetch(url_, options_, "Highlights_highlightsByHighLightCode").then((_response: Response) => {
    return Highlights_processHighlightsByHighLightCode(_response);
  });
}

function Highlights_processHighlightsByHighLightCode(response: Response): Promise<MultifrontTypes.HighlightCodeResponse> {
  const status = response.status;
  let _headers: any = {};
  if (response.headers && response.headers.forEach) {
    response.headers.forEach((v: any, k: any) => (_headers[k] = v));
  }
  if (status === 200) {
    return response.text().then((_responseText) => {
      let result200: any = null;
      result200 = _responseText === "" ? null : (JSON.parse(_responseText) as Models.HighlightCodeResponse);
      return result200;
    });
  } else if (status === 204) {
    return response.text().then((_responseText) => {
      let result204: any = null;
      result204 = _responseText === "" ? null : (JSON.parse(_responseText) as Models.ZnodeErrorDetail);
      return throwException(
        "No Content(Indicates that the request is successfully executed, but the response body does not contain any data.)",
        status,
        _responseText,
        _headers,
        result204
      );
    });
  } else if (status === 400) {
    return response.text().then((_responseText) => {
      let result400: any = null;
      result400 = _responseText === "" ? null : (JSON.parse(_responseText) as Models.ZnodeErrorDetail);
      return throwException("Bad Request(The request contain invalid Data.)", status, _responseText, _headers, result400);
    });
  } else if (status === 500) {
    return response.text().then((_responseText) => {
      let result500: any = null;
      result500 = _responseText === "" ? null : (JSON.parse(_responseText) as Models.ZnodeErrorDetail);
      return throwException("Server Error(Indicates that an error occurred on the server.)", status, _responseText, _headers, result500);
    });
  } else if (status !== 200 && status !== 204) {
    return response.text().then((_responseText) => {
      return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    });
  }
  return Promise.resolve<any>(null as any);
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any }, result?: any): any {
  try {
    if (result !== null && result !== undefined) throw result;
    else throw new Error(message);
  } catch (ex) {
    const parsedRes = response === "" ? null : (JSON.parse(response) as any);
    return parsedRes;
  }
}
